### PR TITLE
Implemented 800, 801, and 808 in Testing setup branch

### PR DESCRIPTION
**Pull request by sebastian-j-ibanez**
#### main_test.go
➕ Test01_PutTelemetry_ValidInput
➕ Test02_PutTelemetry_InvalidInput
➕ Test03_GetTelemetry_Valid
➕ Created test/test1.json
➕ Renamed test/test2.tmpl -> test/test3.tmpl
➕ Made sure tests were in numerical order
➖ Deleted test/test3.json

These changes cover backlog items 800, 801, and 800.

Let me know how it looks! 🧉

### CODE REVIEW

**Review by Inventhrice — APPROVED** [review]
It looks good! I presume that you've run the tests and made sure they all work!

**Comment by sebastian-j-ibanez** [comment]
@Inventhrice it looks like the build failed on the tests I pulled from your branch. Do they look correct to you? I may have done something when I merged.

**Comment by Inventhrice** [comment]
Also who wrote that code for the setupServer() they did such a good job! Along with whoever wrote the tests for the /scripts and /styles path, it's a brilliant piece of code.

**Comment by Inventhrice** [comment]
> @Inventhrice it looks like the build failed on the tests I pulled from your branch. Do they look correct to you? I may have done something when I merged.

@sebastian-j-ibanez The tests look correct, it just seems to be a difference in error messages. What we could do is just modify the test to look for a specific error code as what I'm looking for ai s a 404.

**Comment by sebastian-j-ibanez** [comment]
Invalid test 04 and 05 have been updated. They now pass, and they're checking BOTH the return message and code.

**Pull request merged**
