### PR TITLE
Finished task 742; Adding telemetry input to HTML

### PR DESCRIPTION
**Pull request by AndrewStanley6786**
Telemetry has an input box once again. Also implemented the correct Roll, Pitch & Yaw inputs for Angle functionality. The data can be inputted as angle only, co-ordinate only, or both at once. Removed some buttons that are no longer required.

### CODE REVIEW

**Comment by Inventhrice** [comment]
Now, I'm not sure if I've missed it, but is there any code as to actually send the request out? I can't seem to find it.

**Comment by AndrewStanley6786** [comment]
> Now, I'm not sure if I've missed it, but is there any code as to actually send the request out? I can't seem to find it.

No, I interpreted this as just fixing what had been broken in the HTML. I suppose it does seem more like making the actual routes for sending requests but the HTML page had to at least be fixed first. We can add that as another task

**Comment by Inventhrice** [comment]
Alright, sounds good! Make sure to raise it as a task in Azure and assign it to yourself for the next sprint. In the mean time, the code looks great, and I'll approve the merge.

**Review by Inventhrice — APPROVED** [review]
Great job!

**Pull request merged**
