### PR TITLE
Id493 save json to file

### PR DESCRIPTION
**Pull request by Inventhrice**
Please refer to #13  for details. Original pull request made by @AndrewStanley6786, with the description

"JSON file being wrote to after every get request and every put request for any telemetry data. Also implemented a root route that loads the JSON file data from file."

### CODE REVIEW

**Comment by Inventhrice** [comment]
Anyway, I was supposed to be the reviewer in the other PR. However, because we can't unmerge a PR, I suppose I am the author of this new one. Here is the errors that I caught (for @AndrewStanley6786 ):

image
1. In this situation, if an error is written, no response is ever sent back. This violates REST.

2. For your functions readJSONFromFile() and writeJSONToFile(), it is typical of Go functions to return the actual data and the error code. I'd personally caution against using global variables like this, as it opens up avenues for errors in the future. To fix this, you could have the function instantiate a variable locally to write to, and then return that variable and the error, and then assign telemetryDB to wherever you call it.

image
3. This part of the code confuses me. There are two different responses being sent, and it does not look like the inital "200, data" response would ever get sent due to the proceeding if statement.

**Comment by Inventhrice** [comment]
Also, in this [commit](https://github.com/Inventhrice/GroundStation_CNDH/blob/8b99272c1690fce71332e3e0332c324032dd29ba/main.go), I'm unsure as to why we have two getTelemetry and getRoot? They would be doing the same thing.

**Comment by Inventhrice** [comment]
Addenum to my previous comment: Maybe it isn't worth shifting to route, as I can very clearly pciture some rogue module calling us with no route, hence getting a response we didn't account for. Maybe just using /telemetry is safer because a request sent to us would be intentional (rather than the accidents that can occur by sending ".5/")

**Comment by Inventhrice** [comment]
@AndrewStanley6786 All of the changes look good! Feel free to approve it and merge :)

**Review by AndrewStanley6786 — APPROVED** [review]
Great work, code looks just as it should.

**Pull request merged**
