### PR TITLE
Id635 Live HTML Reload

### PR DESCRIPTION
**Pull request by sebastian-j-ibanez**
### Affected Work Items
- [x] 635
- [x] 874
- [x] 875 

### Changes Made
This is a big PR that spans almost the entire server. Took a ton of work. Please let me know if anything looks off. :mate: 
#### main.go :
:heavy_plus_sign: Added clientList, newClient, closeClient channels variables to manage client connections.
:heavy_plus_sign: Added functionality in PUT /telemetry to pipe incoming telemetry into client channels stored in clientList.
:heavy_plus_sign: Added GET /update endpoint for clients to connect to. This endpoint will also manage client connections using the newClient and closeClient channels.
:heavy_minus_sign: Removed ending / in "/telemetry/"
:heavy_plus_sign: Run manageClientList function in a goroutune (see helper.go changes).
#### helper.go
:heavy_plus_sign: Added manageClientList function. This function will wait for any new items to be added to newClients or closeClients channels. It will either add the new client to the clientList or delete the client from the list and close the connection. 
#### main_test.go
:heavy_minus_sign:  Removed ending / in "/telemetry/"
:heavy_plus_sign: Run manageClientList function in a goroutune (see helper.go changes).
#### UI/index.tmpl
:heavy_plus_sign: Updated the element ids of all the telemetry HTML items so they are unique. This allows us to rewrite specific elements of the page via javascript. 
#### UI/scripts/script.js
:heavy_plus_sign: Added EventSource to listen for update message from /update endpoint (see main.go changes).
:heavy_plus_sign: Added onmessage logic to update the telemetry HTML elements.
:heavy_plus_sign: Added event listener to close the EventSource connection when page is closed.

### Known Issues
- Still need to write unit tests for manageClientList or updateClient functions.
- So far, testing has been done manually using the PUT /telemetry request in test/test.http.

### CODE REVIEW

**Comment by sebastian-j-ibanez** [comment]
DO NOT MERGE QUITE YET.

Just spotted a couple old comments I need to clean up.

**Comment by sebastian-j-ibanez** [comment]
The PR is ready now :smile:

**Review by Inventhrice — CHANGES_REQUESTED** [review]
Found bugs, will document them in the comments.

**Comment by Inventhrice** [comment]
image

I tried testing it, just to see how the code worked, and unfortunately the javascript code replaces something vital (not sure what yet) that erases the CSS from that piece of code (as shown in the image above.)

**Comment by Inventhrice** [comment]
This is a low severity bug, however, when you made these changes
image

You also removed all the CSS that went into it. This isn't really that huge of a deal because the only thing inside the CSS file for those ids was `margin-right: 0.5rem;`, but it did take me by surprise that the webpage rendered correctly.

**Comment by Inventhrice** [comment]
I want to hear your thoughts on this as I am myself not too familiar with how the code interacts with each other, but wouldn't you want this code:
image
in the setupTestServer function?

**Comment by Inventhrice** [comment]
And that concludes my review! Overall, _fantastic_ work! This was a huge undertaking and I appriciate how much effort you've put into this task, and it is a task well done! There were just a few minor things that were missed, but I do not blame you in the slightest for those.

**Comment by Inventhrice** [comment]
I also dealt with the merge conflict for you!

**Comment by sebastian-j-ibanez** [comment]
> I want to hear your thoughts on this as I am myself not too familiar with how the code interacts with each other, but wouldn't you want this code: image in the setupTestServer function?

I initially thought that a goroutine only exists in the scope that it's created. However, after looking it up that is not the case. I can move those to setupTestServer.

**Review by Inventhrice — APPROVED** [review]
Great job! Just make sure to fix the javascript code to still use the template code (like the missing degree signs and all the other stuff), and merge at your own time!

**Pull request merged**
