### PR TITLE
Task 741 and 749: Isolating Ip.cfg code and adding project binaries to gitignore

### PR DESCRIPTION
**Pull request by Inventhrice**
Isolated the code that reads all the IPs into its own function for the main function to look prettier. Also, added the project binaries to the gitignore.

### CODE REVIEW

**Comment by sebastian-j-ibanez** [comment]
Thank you for getting this done! 

Looks good 👍

**Review by sebastian-j-ibanez — CHANGES_REQUESTED** [review]
Everything looks good. Would you mind also putting the structs into a separate file?

**Comment by Inventhrice** [comment]
No

**Review by sebastian-j-ibanez — APPROVED** [review]
Thank you. Looks good 👍

**Pull request merged**
